app:
    resource: "@AppBundle/Controller/"
    type:     annotation

_ynlo_form:
    resource: '@YnloFormBundle/Resources/config/routing.yml'

_ynlo_admin:
    resource: '@YnloAdminBundle/Resources/config/routing.yml'
    prefix:   /admin

